export const CHANGE_LOADING_STATUS = 'CHANGE_LOADING_STATUS';

export const CHANGE_PLAY_STATUS = 'CHANGE_PLAY_STATUS';

export const CHANGE_LYRIC = 'CHANGE_LYRIC';

export const CHANGE_COLLECTOR = 'CHANGE_COLLECTOR';

export const REFRESH_COLLECTOR = 'REFRESH_COLLECTOR';
export const CHANGE_PLAYLIST = 'CHANGE_PLAYLIST';
export const CHANGE_CURRENT_SONG = 'CHANGE_CURRENT_SONG';
